"""
A single cell RNA-seq analysis pipeline.
Author: Ming (Tommy) Tang  04/16/2020
Author: Shariq Madha
"""

configfile: "config.yaml"

include: "rules/common.smk"
# load the samples.json file
FILES = json.load(open(config['SAMPLES_JSON']))
ALL_SAMPLES = sorted(FILES.keys())


REPORTS = expand("Result/{sample}/{sample}_scRNA_report.html", sample = ALL_SAMPLES)

TARGETS = REPORTS

rule all:
    input: TARGETS

include: "rules/sc_rna_map.smk"
include: "rules/sc_rna_qc.smk"
if config["rseqc"]:
    include: "rules/sc_rna_rseqc.smk"
include: "rules/sc_rna_analysis.smk"
include: "rules/sc_rna_report.smk"
